
<center>
    <div id="link">
    
        <select class="form-control col-md-4" onchange="this.options[this.selectedIndex].value && (window.location = this.options[this.selectedIndex].value); " id="select">
            <option value="">Consejos...</option>
            <option value="#1">1. Ten una profunda relación con tus personajes.</option>
            <option value="#2">2. Todo personaje principal tiene un conflicto.</option>
            <option value="#3">3. Define una premisa.</option>
            <option value="#4">4. Define el espacio y tiempo.</option>
            <option value="#5">5. Define la fábula.</option>
            <option value="#6">6. ¿Cómo se narra tu historia? Elige un punto de vista.</option>
        </select>
    </div>
<div class="container col">
    <div id="1"></div>
    <div class="form-row col-md-12" id="row-con">
        <div class="col-md-6 offset-md-1" id="con1">
    
        
            <strong>1. Ten una profunda relación con tus personajes.</strong><br><br>
            
            <li>Las novelas solo funcionan si sus personajes son creíbles.</li>
            <li>Los personajes son creíbles cuando se puede entender la complejidad de su naturaleza humana: cualidades, defectos, contradicciones.</li>
            <li>Los personajes que son completamente buenos o profundamente malos son 
            estereotipos y, por tanto, no son creíbles.</li>
            <li>Con el fin de crear personajes creíbles, tienes que conocer a fondo todo sobre 
            ellos: aspecto fisico, comportamiento, psicología, sociología, ideas, pasiones 
            y su vida antes del comienzo de la novela.</li>
        </div>
        <div class="col-md-3 offset-md-1">
            <img id="consejo1" class=" img-fluid" alt="Responsive image" src="../img/consejo1.png">
        </div>
    </div>
<!-- -----------------------------------------------------------------------------------------------------------------    -->
    <div class="form-row col-md-12" id="row-can">
        <div id="2"></div>
        <div class="col-md-3 offset-md-1">
            <img src="../img/consejo2.png" id="consejo1" class=" img-fluid" alt="Responsive image">
        </div>
        <div class="col-md-6 offset-md-1" id="con1">
            <strong> 2. Todo personaje principal tiene un conflicto.</strong> <br><br>
            <li>La fuerza que impulsa la novela es el conflicto de los personajes principales 
            puede ser una necesidad interior; el deseo de realizarse, de alcanzar una 
            meta, o la consecuencia de una situación externa.</li>
            <li>El conflicto lleva a un personaje a la acción y, por tanto, a cambiar el estado 
            de las cosas.</li>
            <li>Una novela es una historia de un cambio en el estado de las cosas, y de la 
            evolución de los personajes durante este proceso.</li>
            <li>No hay novela sin conflicto.</li>
        </div>
    </div>
<!-- -----------------------------------------------------------------------------------------------------------------    -->
    <div class="form-row col-md-12" id="row-con">
        <div id="3"></div>
        <div class="col-md-6 offset-md-1" id="con1">   
        
            <strong>3. Define una premisa.</strong><br><br>
            La premisa debe contener a toda la novela en una sola frase: sus conflictos y 
            su resolución. <br>
            Vamos a suponer que tu novela trata de un joven que deja su pequeño pueblo 
            para ir a Nueva York, en busca de fortuna como actor. Y finalmente, después 
            de soportar varios fracasos y humillaciones, llega al éxito. En este caso, la 
            premisa podría ser: el deseo de emerger (conflicto) y la determinación para 
            superar los problemas y alcanzar el éxito (resolución). <br>
            La premisa es la guía de la novela: la conclusión solo puede ser alcanzada 
            empezando por el conflicto. <br>
            Si la premisa es clara, todo lo demás sera fácil. Por ejemplo, para nuestro 
            aspirante a actor, su determinación y sentido artístico podría ser revelado 
            desde los primeros capítulos, narrando que durante su infancia paso todo un 
            verano ayudando a su abuela a adornar las paredes de una cocina; creando 
            un enorme y hermoso mosaico con todo tipo de frutas y verduras.
        </div>
        <div class="col-md-3 offset-md-1">
            <img id="consejo1" class=" img-fluid" alt="Responsive image" src="../img/consejo3.png">
        </div>

    </div>
<!-- -----------------------------------------------------------------------------------------------------------------    -->
    <div class="form-row col-md-12" id="row-can">
        <div id="4"></div>
        <div class="col-md-3 offset-md-1">
            <img src="../img/consejo4.png" id="consejo1" class=" img-fluid" alt="Responsive image">
        </div>
        <div class="col-md-6 offset-md-1" id="con1">
            <strong>4. Define el espacio y tiempo.</strong> <br><br>
            <li>Tus personajes actúan en un espacio y tiempo determinado, y esto debería 
            influir profundamente en ellos.</li>
            <li>Por ejemplo, algo que podría resultar muy escandaloso en un pequeño pueblo 
            en 1800, probablemente de igual en la Nueva York del 2010.</li>
            <li>Por lo tanto, con el fin de hacer la novela creíble, es esencial entender  
            previamente su entorno (el espacio/tiempo) y hacer que este influya 
            coherentemente en los personajes y situaciones.</li>
        </div>
    </div>
<!-- -----------------------------------------------------------------------------------------------------------------    -->
    <div class="form-row col-md-12" id="row-con">
        <div id="5"></div>
        <div class="col-md-6 offset-md-1" id="con1">   
        
        <strong>5. Define la fábula.</strong> <br><br>
        <li>La fábula es la narración de los eventos ordenados en una secuencia lógica-temporal.</li>
        <li>En primer lugar, tienes que definir brevemente la fábula de la novela, con 
        independencia de la trama, que es el orden en que se presentan los 
        acontecimientos (narración lineal, flashbacks, previews).</li>
        <li>Una vez que haya definido completamente la fábula, será fácil para ti 
        determinar la forma más eficaz para desarrollar la trama.</li>
        </div>
        <div class="col-md-3 offset-md-1">
            <img id="consejo1" class=" img-fluid" alt="Responsive image" src="../img/consejo5.png">
        </div>

    </div>
    <!-- -----------------------------------------------------------------------------------------------------------------    -->
    <div class="form-row col-md-12" id="row-can">
    <div id="6"></div>
        <div class="col-md-3 offset-md-1">
            <img src="../img/consejo6.png" id="consejo" class=" img-fluid" alt="Responsive image">
        </div>
        <div class="col-md-6 offset-md-1" id="con1">
        <strong>6. ¿Cómo se narra tu historia? Elige un punto de vista.</strong> <br><br>
        Cada punto de vista tiene ventajas específicas. Aquí tienes un vistazo rapido 
        de cada uno: <br>
        <b>Primera persona:</b> la historia es narrada en primera persona por uno de los 
        personajes principales. Las escenas se cuentan a través de los sentidos y 
        los pensamientos del personaje: esto significa que la narración debe ser 
        coherente respecto a su inteligencia y vocabulario. Solo pueden ser narrados 
        los acontecimientos que el personaje realmente conoce. <br>
        <b>Primera persona secundaria:</b> La historia es narrada en primera persona por un 
        personaje secundario, quien no es el protagonista de los eventos. Este punto 
        de vista suele usarse cuando el personaje principal no esta consciente y, por 
        tanto, no es capaz de contar su historia. El narrador no conoce los 
        pensamientos del personaje principal y solo puede narrar los eventos que ha 
        presenciado. <br>
        <b>Tercera persona limitada:</b> La historia es narrada en tercera persona por un 
        narrador externo, el cual solo tiene acceso a los principales pensamientos y 
        acciones de los personajes. La narración es mas desenfrenada que en 
        primera persona y no necesariamente coherente con la inteligencia y lenguaje 
        del personaje. El personaje narra únicamente los eventos que conoce. <br>
        <b>Tercera persona omnisciente:</b> La historia es narrada en tercera persona por 
        un narrador externo el cual tiene acceso a los pensamientos de todos los 
        pensamientos, así como a todos los eventos del pasado, presente y futuro; 
        incluyendo eventos que ningún personaje conoce. <br>
        <b>Tercera persona objetiva:</b> La escena es narrada en tercera persona por un 
        narrador externo que no tiene acceso a los pensamientos de los personajes. <br>
        La narración tiene un estilo periodístico. El narrador tiene acceso a todos los 
        eventos, pero la narración se debe desarrollar solo con acciones y diálogos. <br>
        <b>Segunda persona:</b> La escena es narrada en segunda persona por un narrador 
        externo que se dirige directamente al lector.
        </div>
    </div>
</div>

</center>