<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Leer</title>
</head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" 
integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<link rel="stylesheet" href="css/estilo.css">
<body>
    <br>
    <br>
        

    <br>
    <br>
    <div class="container col">
        <center>

            <div id="hoja" class="col-10">
                <br>
    
                <h2><center>Titulo de la obra</center> </h2><br>
                <img src="img/documento.jpg" class="img-fluid rounded mx-auto d-block"><br>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed id quibusdam minima eum velit et harum, quae aspernatur similique incidunt quasi, reprehenderit assumenda ratione neque quisquam dolore amet quos in.
                Repudiandae tempore laborum pariatur neque accusamus aliquid quidem magni, quaerat quia! Repellendus illo molestiae eligendi ab! Error aut nostrum vitae assumenda facilis! Sapiente praesentium soluta alias iste, ullam explicabo dolores.
                A nam excepturi delectus recusandae non aliquam distinctio in itaque placeat iure dolor, molestiae commodi odit facere architecto! Fugit libero sit sequi ipsa provident esse aut tempora aliquid illo aperiam.
                Vel repellat voluptas quos praesentium autem quo laudantium, facilis optio dolorem corporis rerum iste debitis quae dolore sit cumque fugit quod dolor iure voluptates esse labore! Culpa explicabo doloribus minus.
                Atque expedita aliquid earum culpa similique pariatur laudantium quasi quam architecto neque at, iste, mollitia illum ipsam libero aut placeat facere, dolores optio ad! Reprehenderit quia odit dolore mollitia ea!
                Consequatur illum placeat possimus adipisci unde suscipit quos facere eius quas sed consequuntur modi blanditiis, dolorem debitis quis nam obcaecati quasi dolore dicta error excepturi iste vel vitae veritatis? Minus.
                Veritatis a aliquid et neque unde nesciunt amet necessitatibus molestiae incidunt ad qui, sed natus facere pariatur? Nulla harum excepturi debitis repellat sunt perferendis, eaque explicabo similique voluptas, in quos!
                Perspiciatis expedita quisquam rem eaque. <br><br> Mollitia ea illo facilis ut illum voluptates consequatur dolorem! Veniam, ea eaque modi aliquam harum ullam sapiente sed consequuntur tempora inventore quis iure voluptate error?
                Quo, numquam! Nobis ipsa quod repellendus, nam veniam asperiores modi repudiandae vero eveniet recusandae ducimus porro aliquam cumque reiciendis mollitia culpa illumdolores perferendis animi non beatae minus ab? Qui.
                Ducimus, impedit, obcaecati nam unde quia ut voluptate, corrupti possimus odio placeat quae dolorum fugit sunt doloribus vel modi! Sit ducimus repellendus vero eaque a tempora ipsa aliquid veniam architecto!
                In nihil nam nesciunt ipsa ut magni assumenda quo voluptate perferendis. <br><br> Enim cumque id repellendus, officia labore ullam vitae consequuntur? Quas ducimus iure fugit animi magni provident delectus molestias cum.
                Exercitationem impedit facilis, aperiam ut modi ullam reiciendis cumque consectetur aliquam fugit numquam veritatis id quo non quisquam repellat nesciunt esse cum perspiciatis voluptatum totam corporis voluptatem? Odio, veritatis cum?
                Nulla quos inventore repellendus quas eaque atque debitis, iste earum ipsum veniam nobis! Reprehenderit id modi assumenda, ad laudantium dolorem non tempore possimus ab? Quam autem alias maiores fuga. Earum?
                Consequatur labore iure sed itaque corporis voluptatem? Delectus labore voluptatem placeat optio ea eos aut voluptatibus sed eligendi earum amet, neque quibusdam eveniet libero animi tenetur omnis repellendus, consequatur officia.
                <br><br> Eveniet dolor quo consequatur voluptatem obcaecati sunt hic excepturi modi earum, nulla nemo labore? Debitis porro eum rem quos architecto facilis et doloremque, adipisci temporibus, excepturi cupiditate voluptatum, error sit.
                Quisquam facilis minus vel culpa assumenda rem id ea, optio debitis ipsum error laborum. Eius non minus maiores laboriosam ducimus. Ad recusandae et, tempora cupiditate itaque est praesentium ipsum earum!
                Distinctio fuga molestiae voluptates sapiente soluta libero nobis maiores? Quaerat libero cumque esse id dolor non ipsa, deleniti facilis eaque, delectus cum alias magni, nobis ullam aliquam incidunt. Quasi, illum?
                Maiores dolor consequatur deleniti id, iste quisquam illo! Quasi nisi vel soluta dolorum, veniam eum! Voluptatem, tempora voluptate. Quas perspiciatis suscipit, deleniti quam adipisci sed earum consequatur quod debitis perferendis.
                Deleniti voluptate fugit dicta facilis, ut molestias illum pariatur nulla expedita fuga maiores voluptatem natus quod tenetur enim odit eius illo corporis culpa temporibus! Excepturi neque reprehenderit expedita corporis commodi!
                <br><br> </div>
            
            </div><br>
            <div class="container col">
                <center>
        
                    <div id="hoja" class="col-10">
                        <br>
            Deleniti est quod voluptates beatae. Voluptatum itaque obcaecati nemo dolores eligendi reiciendis earum distinctio modi alias, vel dolorem quo ex exercitationem enim, minus nihil repellat, amet vitae nam laboriosam ducimus.
                At adipisci nostrum sapiente deserunt reprehenderit, aspernatur modi temporibus, perferendis vitae eveniet nobis dolores libero quaerat non aut est odio aliquid asperiores voluptatum. Nostrum recusandae natus nisi corrupti illo eum!
                Dolores, omnis officia! Similique, dicta iusto sequi quidem quia aperiam, neque, dolorum illo quo veritatis quibusdam? Repellendus nisi sunt blanditiis! Vero autem voluptas cum possimus ex reiciendis praesentium aliquid? Excepturi?
                Porro sint eius excepturi unde. Perferendis consequatur maiores enim omnis pariatur, tempora consequuntur, dolore nam amet error fuga facilis neque fugit. Voluptas nam, animi pariatur obcaecati maxime vero nesciunt placeat!
                Assumenda exercitationem debitis totam adipisci, illum atque. Minima sed nostrum veritatis voluptatem nihil aliquam explicabo. Ex nam perspiciatis fugit illum possimus rem placeat consectetur, omnis nemo beatae ea nulla optio!
                <br><br> Aspernatur dolor dignissimos ad sunt officiis doloribus iusto nobis eos officia blanditiis architecto nemo quis, eius porro perspiciatis enim labore facilis esse libero nihil repellendus? Commodi error facilis maiores nostrum.
                Quia error asperiores molestias eligendi ipsa cum laborum eum illo, est, sed sunt dolor, natus corporis! Error, sint deserunt. Accusantium mollitia pariatur laboriosam ipsa quo impedit, provident fugit voluptas. Et!
                Architecto beatae libero error. Similique sequi quia, architecto quidem accusamus culpa, ea eum in optio soluta repellendus quae magnam! Voluptatibus sequi magnam eos veritatis reiciendis iusto exercitationem itaque modi? Unde.
                Obcaecati tenetur nam aliquam cumque atque, facere architecto facilis libero error laboriosam optio ipsa debitis? Autem velit dolorem possimus eveniet, esse ex recusandae laudantium exercitationem, alias soluta nihil quis accusamus.
                Culpa incidunt facilis porro accusantium excepturi perferendis, provident, placeat exercitationem accusamus vero, ipsam non veniam nam rerum. Illo cupiditate maiores velit aperiam quibusdam tenetur architecto. Atque fugit esse earum sequi.
                Praesentium molestias rerum ducimus quisquam deserunt velit aspernatur, esse cum maiores aliquid molestiae itaque atque sequi mollitia, a quos reprehenderit quae. Unde mollitia nemo reprehenderit nihil quod odio optio quibusdam.</p>
                <footer class="blockquote-footer"> Autor del guión<cite title="Source Title"> Cita del autor</cite></footer>
                <br> <br><br><br><br><br><br><br><br><br><br><br><br>
                <br> <br><br><br><br><br><br><br><br><br><br><br><br>
            </div>
            
        </div><br><br>
        
        </center>
   
    <div class="container col-10" id="container">
        <div class="row">
            <div class="offset-7">
                <ion-icon name="thumbs-up" id="icon"></ion-icon>
            </div>
            <div class="offset-1">
                <ion-icon name="thumbs-down" id="icon"></ion-icon>

            </div>
        </div>
        <hr>
        <div class="form-inline">
            <label>Cometarios:</label>
            <textarea class="form-control col-8"></textarea>
            <button class="col-1 btn btn-success btn-lg"><ion-icon name="send" size="small"></ion-icon></button>
          </div>
          
    </div>
    <button class="btn btn-primary" style="position: fixed; left: 85%; top: 10%;" onclick="location.href='leer.html#tema1'"><ion-icon name="chatbox-outline" size="large"></ion-icon></button>  
   <a name="tema1"></a>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/ionicons@5.1.2/dist/ionicons.js"></script>
</body>
</html>