<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Olvidó su contraseña</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" 
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="../css/estilo.css">
</head>
<body>
    <br>    <br> 
    <div class="container col-md-4 col-xs-8" id="container" style="padding: 15px;">
        <center><footer>- WRITERS CAISAN -</footer>
            <img id="logo" src="../img/ICONO.jpg" class="img-fluid" style="height:150px; width: 150px; border-radius: 100%;">
        </center>
        <center>
            <h3>Recuperación de cotraseña.</h3><br>
            <img src="../img/verifica.jpg" class="img-fluid rounded" alt="Responsive image" style="border: solid 0.5px; height: 150px;">
        </center><br>
        <h4>Obtener un código de verificación.</h4>
        <p><b> Writer Caisan</b> enviará un código de verificación al correo con el que se registró.</p><hr>
        <div class="row">
            <button class="btn btn-primary offset-md-3 col-md-6" onclick="location.href='codigo.html'">Enviar</button>
        </div><br>
         
        

    </div>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" 
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="css/estilo.css">
</body>
</html>