<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="shortcut icon" href="../img/ICONO.svg">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" 
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="../css/estilo.css">
</head>
<body>
    
    <div id="cabecera">
    <img id="logo" src="../img/LOGO.svg">
    </div>



    <div class="container">
        <h1>
            <center>
                INICIO DE SESIÓN <!-- Titulo de la página -->
            </center>
        </h1>
        <center>No estás registrado? <a href="registro.phtml">Crea una cuenta.</a>.</center> <!-- Para redireccionar a regitro -->
    </div>
    <br><br>
    
    <div class="container col-md-10"> 
        <div class="form-row">
            <div class="col-md-6">
                <center>
                <img id="logo" src="../img/ICONO.svg" class="img-fluid" style="height:150px; width: 150px; border-radius: 50%;">
                <p>
                    <h2>¡Usa tu imaginación!</h2><br>
                    <h4>Crea tus propios guiones, y publicalos.</h4>
                </p>
                </center>
            </div>
            <div class="col-md-4" id="container" style="padding: 15px;">
    
                <form action="../models/sesion.php" method="post"> <!-- Formulario -->
                    <div class="form-row">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1"><img src="../icons/a.svg"></span>
                        </div>
                        <input type="email" class="form-control" name="email" placeholder="Correo electrónico" style="background: none;" required>
                        </div>
                    </div>
                    <br>
                    <div class="form-row">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1"><img src="../icons/key.svg"></span>
                        </div>
                        <input type="password" class="form-control" name="contraseña" placeholder="Contraseña" style="background: none;" required>
                    </div></div><br>
                    
                    <a href="olvido.phtml">¿Olvidaste tu contraseña? </a><br><br>
                    <center>
                        <button class="btn btn-primary col-md-6">Ingresar</button>
        
                    </center>

            
                </form>
                <hr>
                <center>
                        <button class="btn btn-success col-md-6"  onclick="location.href='visitante.html'">Entrar como visitante</button>
                        <small id="emailHelp" class="form-text text-muted">Podrás ver algunas de las obras, pero no podras comentar ni reaccionar.</small>
                </center>

            </div>

        </div>
    </div>    



    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    
</body>
</html>