<div class="container col--md-10">
    <center>
        <div class="col-md-5" id="text">
            <img src="../img/segu.png"  class="img-fluid" id="seguro">
            <p>
                <b>Writers Caisan </b> protege tu contraseña con sifrado de extremo a
                extremo. Esto quiere decir que tu contraseña es solo para ti, nisiquiera
                <b>Writers caisan </b> podrá saber su contraseña.
            </p>
            <hr>
            <hr>
            <button class="btn btn-danger btn" data-toggle="modal" data-target="#contraseña">Cambiar Contraseña</button>
        </div>
    </center>
</div>



<div class="modal fade" id="contraseña">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
    <div class="modal-body">
        <h2>Cambiar contraseña</h2>
        <hr>
        <form method="post" action="../models/seguridad.php">
          <div class="form-group">
          <div class="form-group col">
                <div class="input-group mb-3">
                <div class="input-group-prepend">
                  <span class="input-group-text" id="basic-addon1"><img src="../icons/key.svg"></i></span>
                </div>
            <input type="password" class="form-control" id="recipient-name" placeholder="Contraseña actual" name="pass0" required>
          </div></div>
          <hr><hr>
          <div class="form-group">
          <div class="form-group col">
                <div class="input-group mb-3">
                <div class="input-group-prepend">
                  <span class="input-group-text" id="basic-addon1"><img src="../icons/key.svg"></i></span>
                </div>
            <input type="password" class="form-control" id="recipient-name" placeholder="Contraseña nueva" name="pass1" required>
          </div></div>
          <div class="form-group">
            <div class="form-group col">
                <div class="input-group mb-3">
                <div class="input-group-prepend">
                  <span class="input-group-text" id="basic-addon1"><img src="../icons/key.svg"></i></span>
                </div>
            <input type="password" class="form-control" id="recipient-name" placeholder="Vuelve a escribir la contraseña nueva" name="pass2" required>
          </div></div>
          
          <div class="modal-footer">
            <input type="submit"  class="btn btn-primary" value="Actualizar contraseña">
        </form>    
            <button type="button" class="btn btn-secondary" data-dismiss="modal">X</button>
      </div>
      
    </div>
  </div>
</div>    
